-- Esquema de test inferido del código de LaCanchita
CREATE TABLE IF NOT EXISTS perfil (
  PERFIL_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PERFIL_NOMBRE VARCHAR(50) NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usuarios (
  USUARIOS_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  USUARIOS_NOMBRE VARCHAR(80) NOT NULL,
  USUARIOS_APELLIDO VARCHAR(80) NOT NULL DEFAULT '',
  USUARIOS_DNI VARCHAR(30) NULL,
  USUARIOS_EMAIL VARCHAR(150) NOT NULL,
  USUARIOS_TELEFONO VARCHAR(30) NULL,
  USUARIOS_PASSWORD VARCHAR(255) NOT NULL,
  PERFIL_ID INT UNSIGNED NOT NULL DEFAULT 5,
  DUENO_ID INT UNSIGNED NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS provincia (
  PROVINCIA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PROVINCIA_NOMBRE VARCHAR(80) NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partido (
  PARTIDO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PARTIDO_NOMBRE VARCHAR(80) NOT NULL,
  PROVINCIA_ID INT UNSIGNED NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS localidad (
  LOCALIDAD_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  LOCALIDAD_NOMBRE VARCHAR(80) NOT NULL,
  PARTIDO_ID INT UNSIGNED NOT NULL,
  PROVINCIA_ID INT UNSIGNED NULL,   -- denormalizado: el Dashboard lo lee para el geo embebido
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tipo_complejo (
  TIPO_COMPLEJO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TIPO_COMPLEJO_NOMBRE VARCHAR(80) NOT NULL,
  TIPO_COMPLEJO_ICONO VARCHAR(60) NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tipo_cancha (
  TIPO_CANCHA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TIPO_CANCHA_NOMBRE VARCHAR(80) NOT NULL,
  TIPO_CANCHA_ICONO VARCHAR(60) NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS medio_pago (
  MEDIO_PAGO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  MEDIO_PAGO_NOMBRE VARCHAR(80) NOT NULL,
  MEDIO_PAGO_ICONO VARCHAR(60) NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS complejo (
  COMPLEJO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  COMPLEJO_NOMBRE VARCHAR(120) NOT NULL,
  COMPLEJO_DIRECCION VARCHAR(200) NOT NULL DEFAULT '',
  COMPLEJO_TELEFONO VARCHAR(30) NULL,
  COMPLEJO_EMAIL VARCHAR(150) NULL,
  COMPLEJO_INSTAGRAM VARCHAR(150) NULL,
  COMPLEJO_DESCRIPCION TEXT NULL,
  LOCALIDAD_ID INT UNSIGNED NULL,
  TIPO_COMPLEJO_ID INT UNSIGNED NULL,
  USUARIOS_ID INT UNSIGNED NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS complejo_actividad (
  COMPLEJO_ID INT UNSIGNED NOT NULL,
  TIPO_CANCHA_ID INT UNSIGNED NOT NULL,
  ACTIVIDAD_DESTACADA TINYINT(1) NOT NULL DEFAULT 0,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_ca (COMPLEJO_ID, TIPO_CANCHA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS complejo_horario_atencion (
  ATENCION_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  COMPLEJO_ID INT UNSIGNED NOT NULL,
  DIA_ID TINYINT UNSIGNED NOT NULL,
  ATENCION_HORA_APERTURA TIME NOT NULL,
  ATENCION_HORA_CIERRE TIME NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cancha (
  CANCHA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CANCHA_NOMBRE VARCHAR(100) NOT NULL,
  CANCHA_DESCRIPCION TEXT NULL,
  TIPO_CANCHA_ID INT UNSIGNED NULL,
  COMPLEJO_ID INT UNSIGNED NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cancha_encargado (
  CANCHA_ID INT UNSIGNED NOT NULL,
  USUARIOS_ID INT UNSIGNED NOT NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_ce (CANCHA_ID, USUARIOS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS franja_horaria (
  FRANJA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CANCHA_ID INT UNSIGNED NOT NULL,
  FRANJA_HORA_INICIO TIME NOT NULL,
  FRANJA_HORA_FIN TIME NOT NULL,
  FRANJA_PRECIO DECIMAL(10,2) NOT NULL DEFAULT 0,
  FRANJA_SENA DECIMAL(10,2) NOT NULL DEFAULT 0,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS franja_dia (
  FRANJA_ID INT UNSIGNED NOT NULL,
  DIA_ID TINYINT UNSIGNED NOT NULL,
  UNIQUE KEY uq_fd (FRANJA_ID, DIA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reserva (
  RESERVA_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CANCHA_ID INT UNSIGNED NOT NULL,
  FRANJA_ID INT UNSIGNED NOT NULL,
  USUARIOS_ID INT UNSIGNED NOT NULL,
  RESERVA_FECHA DATE NOT NULL,
  RESERVA_HORA_INICIO TIME NOT NULL,
  RESERVA_HORA_FIN TIME NOT NULL,
  RESERVA_PRECIO DECIMAL(10,2) NOT NULL DEFAULT 0,
  RESERVA_SENA DECIMAL(10,2) NOT NULL DEFAULT 0,
  RESERVA_ESTADO VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  RESERVA_ES_FIJA TINYINT(1) NOT NULL DEFAULT 0,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pago (
  PAGO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  RESERVA_ID INT UNSIGNED NOT NULL,
  PAGO_MONTO DECIMAL(10,2) NOT NULL,
  PAGO_TIPO VARCHAR(20) NOT NULL DEFAULT 'parcial',
  PAGO_MEDIO VARCHAR(30) NOT NULL DEFAULT 'efectivo',
  PAGO_OBSERVACION VARCHAR(200) NULL,
  USUARIOS_ID INT UNSIGNED NULL,
  PAGO_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS turno_fijo (
  TURNO_FIJO_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CANCHA_ID INT UNSIGNED NOT NULL,
  FRANJA_ID INT UNSIGNED NULL,
  USUARIOS_ID INT UNSIGNED NULL,
  TURNO_FIJO_DIA TINYINT UNSIGNED NOT NULL,
  TURNO_FIJO_HORA_INICIO TIME NOT NULL,
  TURNO_FIJO_HORA_FIN TIME NOT NULL,
  TURNO_FIJO_PRECIO DECIMAL(10,2) NULL,
  TURNO_FIJO_FECHA_DESDE DATE NOT NULL,
  TURNO_FIJO_FECHA_HASTA DATE NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cierre_cancha (
  CIERRE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  COMPLEJO_ID INT UNSIGNED NULL,
  CANCHA_ID INT UNSIGNED NULL,
  CIERRE_FECHA_DESDE DATE NOT NULL,
  CIERRE_FECHA_HASTA DATE NOT NULL,
  CIERRE_HORA_DESDE TIME NULL,
  CIERRE_HORA_HASTA TIME NULL,
  CIERRE_MOTIVO VARCHAR(200) NULL,
  ACTIVO TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
