-- Suscripciones Web Push por usuario
CREATE TABLE IF NOT EXISTS push_subscriptions (
    SUB_ID      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USUARIOS_ID INT UNSIGNED NOT NULL,
    ENDPOINT    TEXT NOT NULL,
    P256DH      VARCHAR(255) NOT NULL,
    AUTH        VARCHAR(100) NOT NULL,
    USER_AGENT  VARCHAR(200) DEFAULT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_endpoint (ENDPOINT(200))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
